version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres:5432/postgres
      - REDIS_URL=redis://redis:6379/0
      - WEBHOOK_HMAC_SECRET=dev-secret
      - CONFIG_VERSION=2025-08-07
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"
    command: uvicorn app.app:app --host 0.0.0.0 --port 8000 --loop uvloop --http httptools --workers 1

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres:5432/postgres
      - REDIS_URL=redis://redis:6379/0
      - WEBHOOK_HMAC_SECRET=dev-secret
      - CONFIG_VERSION=2025-08-07
    depends_on:
      - postgres
      - redis
    command: python -m app.run_worker

  cron:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres:5432/postgres
      - REDIS_URL=redis://redis:6379/0
      - CONFIG_VERSION=2025-08-07
    depends_on:
      - postgres
      - redis
    command: python -m app.run_cron

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  pgdata: {}


